apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "workbench-operator.fullname" . }}-manager-role
  labels:
  {{- include "workbench-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
- apiGroups:
  - default.chorus-tre.ch
  resources:
  - workbenches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - default.chorus-tre.ch
  resources:
  - workbenches/finalizers
  verbs:
  - update
- apiGroups:
  - default.chorus-tre.ch
  resources:
  - workbenches/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "workbench-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "workbench-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "workbench-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "workbench-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'