resources:
  - manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: controller
    newName: registry.chorus-tre.local/chorus/workbench-operator
    newTag: 0.2.3
