---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-default-chorus-tre-ch-v1alpha1-workbench
  failurePolicy: Fail
  name: mworkbench.kb.io
  rules:
  - apiGroups:
    - default.chorus-tre.ch
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workbenches
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-default-chorus-tre-ch-v1alpha1-workbench
  failurePolicy: Fail
  name: vworkbench.kb.io
  rules:
  - apiGroups:
    - default.chorus-tre.ch
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workbenches
  sideEffects: None
